language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls