language: php

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_4712efbae1df_key -iv $encrypted_4712efbae1df_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls
